[package]
name = "graph-mock"
version = "0.22.0"
edition = "2018"

[dependencies]
futures = "0.3.13"
graphql-parser = "0.3"
graph = { path = "../graph" }
graph-graphql = { path = "../graphql" }
mockall = "0.13"
rand = "0.8.3"
