[package]
name = "graph-server-metrics"
version = "0.22.0"
edition = "2018"

[dependencies]
futures = "0.3.13"
graph = { path = "../../graph" }
http = "1.4"
hyper = "1.8"
lazy_static = "1.5.0"
serde = "1.0"
